Vagrant.configure("2") do |config|
    config.vm.box = "generic/netbsd9"
    # config.vm.network "public_network"
    config.disksize.size = '20GB'
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "2"
    end
  end